spring:
  datasource:
    url: jdbc:mysql://localhost:3333/oi
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
