version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oi
          MYSQL_USER: username
          MYSQL_PASSWORD: password
          TZ: Asia/Tokyo

    working_directory: ~/oi-back

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run tests and lint!
      - run: gradle check
